### ISSUE TITLE
Unclear how to add/configure integration

### ISSUE THREAD

**Issue by kalbfuss** [chkuendig/hass-amphiro-ble#4]
Hey there!

From the Readme it is unfortunately not clear to me how to install this integration. I have added the page as custom repository to HACS and installed the integration. When I attempt to add the integration afterwards, I only get the following screen:

![Bildschirmfoto vom 2023-06-03 22-10-10](https://github.com/chkuendig/hass-amphiro-ble/assets/6892738/11bc12e6-90f9-4bb1-9de9-5bfc5c34ba97)

I am using HA 2023.5.4. Bluetooth is enabled via an ESPHome bluetooth proxy, which works quite well with the Xiaomi BLE integration.

What am I missing? Does the integration still work with the latest version of Home Assistant?

**Comment by mihsu81** [comment]
The device is automatically discovered and added if supported.

**Comment by chkuendig** [comment]
@mihsu81 is correct, there is no configuration required as with other Home Assistant sensors that have autodiscovery.
