### ISSUE TITLE
[Issue] The integration only receives data the first 2 seconds

### ISSUE THREAD

**Issue by mihsu81** [chkuendig/hass-amphiro-ble#5]
Hi @chkuendig and thank you for this integration.
I have the Hansa version of the Amphiro DHS.
The device is properly detected but it is receiving data only for the first 2 seconds after opening the tap. If I close the tap after another let's say 10 seconds and open the tap again, the values get updated with the missing quantities, and get updated for another 2 seconds and stop updating again.
Any idea what could be the reason?

I don't see any errors in the HA logs.

Thanks in advance for your help.

**Comment by chkuendig** [comment]
Hi @mihsu81 

Unfortunately I don't know what might be causing this and haven't encountered this issue myself. One option to debug this would be to see what other packages are broadcasted (if any), but it's been a while and I don't remember the tutorials I used back when I did this type of BTLE work :(

**Comment by bipsendk** [comment]
Home assistant logs will typically log whatever BLE announcements, that are found (either directly or via BLE proxy). That will probably be the first place to look...

**Comment by mihsu81** [comment]
I had an ESP32 nearby with https://github.com/bipsendk/oras-shower, which seems to connect to the shower head, after which the shower head stops broadcasting. After powering off that ESP32, HA was able to receive data continuously.
I had tried this step before, but it didn't make a difference for some reason.
Thank you.
